version: '3'
services:
  toks-personal:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - 1987:3000
     # - 3800:3011
    working_dir: /usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
   # volumes:
   #   - ./:/app
   #   - /app/node_modules
    tty: true
    stdin_open: true
    # working_dir: /app
volumes:
  src: